### ISSUE TITLE
Speech to text output not working

### ISSUE THREAD

**Issue by mcleanalec** [B4PT0R/streamlit-mic-recorder#4] opened 2023-12-18 22:55 UTC
I am trying to run run the STT method on my local machine but for some reason its not picking up my audio - Ive enabled everything on my end to allow the mic to pick up sound but its not getting picked up. 

The button is present:
![Screenshot 2023-12-18 at 5 53 18 PM](https://github.com/B4PT0R/streamlit-mic-recorder/assets/13340535/4e17f7a0-ec7e-491a-afeb-b955df750e1e)

When I inspect the page, I get the following error message in my console:

```Traceback (most recent call last):
  File ".../venv/lib/python3.9/site-packages/streamlit/web/server/component_request_handler.py", line 55, in get
    with open(abspath, "rb") as file:
FileNotFoundError: [Errno 2] No such file or directory: '.../venv/lib/python3.9/site-packages/streamlit_mic_recorder/frontend/build/bootstrap.min.css.map'
```

Any thoughts you have would be helpful!

**Comment by B4PT0R** [comment] 2023-12-20 10:12
Hello,

You're the first one reporting this issue. Seems to work fine for other people.
Difficult to tell what's going wrong without knowing more about your setting.

What browser are you using ?
Is the mic on which you'd like to record the default one in your audio settings ?

First make sure you use the latest version of the package:
```$ pip install streamlit_mic_recorder --upgrade```
or uninstall and reinstall to start with a fresh install.

Have you tried using only the mic_recorder function ? (Idk, maybe the problem comes from the additional layer of speech recognition introduced in the speech_to_text function)

Try running locally this simple test script and tell me the outcome:

```python
import streamlit as st
from streamlit_mic_recorder import mic_recorder

audio=mic_recorder()
if audio:
    st.audio(audio['bytes'])
```

Also, make sure you allow the app to record sound from the mic. (your browser should ask for permission to record sound the first time you use the component)

**Comment by mcleanalec** [comment] 2023-12-20 19:02
The mic works and I am able to record my voice but when it tries to convert it to text, it looks like nothing is being recorded?

![Screenshot 2023-12-20 at 2 00 25 PM](https://github.com/B4PT0R/streamlit-mic-recorder/assets/13340535/4b882932-9ebd-4c9c-a3b5-b98d9a6c6c69)

I even tried using the `speech_recognition` package directly, but that did't work either. Maybe this could be the issue?
![Screenshot 2023-12-20 at 2 02 02 PM](https://github.com/B4PT0R/streamlit-mic-recorder/assets/13340535/ad66804d-4c63-4c29-b6b5-85e0f90fcfe1)

**Comment by B4PT0R** [comment] 2023-12-20 19:47
Weird...

Just tried running the test, all works fine for me.

If the audio gets recorded and comes out of the component, the issue must have to do with the speech_recognition module indeed.

Maybe try with a fresh install of the speech_recognition module, or change version ?

Do you get any warning in the terminal from the recognize_google function ?

**Comment by B4PT0R** [comment] 2023-12-20 20:20
I've tried uprading to the latest version of SpeechRecognition, no problem encountered.
Maybe there is something preventing the package to work correctly on your setup.
You could try creating a virtual environment, installing the required packages afresh and run similar tests there.
If it works in the venv it probably means there is a package conflict of some sort in your python setup.

**Comment by B4PT0R** [comment] 2023-12-23 23:50
Closing the issue as it doesn't seem to be related to the widget itself.

**Closed by B4PT0R** 2023-12-23 23:50 UTC

**Comment by coreyryanhanson** [comment] 2024-08-19 04:32
I'd like to reopen this. It seems others get this error too in similar issues. I don't have a complete grasp on the bug, but I have a feeling it stems from a dependency of some sort being taken for granted.

The reason being that this plugin works great if I install it on my PC. But... If I spin up a server somewhere like runpod and do a fresh venv install. I get this same error with no verbosity other than that hard to troubleshoot error. At the very least it might help if the root cause of this bug can be discovered and a way to prevent it is documented.

**Comment by coreyryanhanson** [comment] 2024-08-19 04:33
@B4PT0R
